version: '2'
services:
    infohub-app:
        image: infohub
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://infohub-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=infohub
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    infohub-mongodb:
        extends:
            file: mongodb.yml
            service: infohub-mongodb
